[package]
name = "interception"
version = "0.1.0"
edition = "2018"
publish = false

[build-dependencies]
cc = "1.0"

[dependencies]
bitflags = "1.2.1"
num_enum = "0.5.0"
serde = { version = "1.0.114", features = ["derive"] }