[package]
name = "slidershim"
version = "0.1.0"
description = "slidershim"
authors = ["4yn"]
license = ""
repository = ""
default-run = "slidershim"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.14"
env_logger = "0.9.0"
tauri = { version = "1.0.0-beta.8", features = ["api-all", "system-tray"] }

futures = "0.3.19"
futures-util = "0.3.19"
async-trait = "0.1.52"
tokio = { version="1.16.1", features=["rt-multi-thread","macros"] }
tokio-util = "0.6.9"

directories = "4.0.1"
rusb = "0.9.0"
serialport = "4.0.1"
vigem-client = "0.1.1"
palette = "0.6.0"
winapi = "0.3.9"

hyper = { version="0.14.16", features=["server", "http1", "http2", "tcp", "stream", "runtime"] }
path-clean = "0.1.0"
tungstenite = { version="0.16.0", default-features=false }
tokio-tungstenite = "0.16.1"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
